'use strict';
const $ = id => document.getElementById(id); let captured = null; let settings;
const status = (text, error=false) => { $('status').textContent=text; $('status').style.color=error?'#ff8a80':'#aebac1'; };
const gatewayForm = () => ({ name:$('gateway-name').value,baseUrl:$('base-url').value,apiMode:$('api-mode').value,model:$('model').value,webSearchCapable:$('web-capable').checked,extraHeaders:$('headers').value });
function renderProfiles(){ $('profiles').replaceChildren(); $('profile').replaceChildren(); $('default-profile').replaceChildren(); for(const p of settings.profiles){ for(const select of [$('profile'),$('default-profile')]) select.add(new Option(p.name,p.id)); const card=document.createElement('div'); card.className='profile-card'; card.dataset.id=p.id; card.innerHTML='<input class="pname" maxlength="80"><textarea class="pprompt" maxlength="8000"></textarea><button class="danger remove" type="button">Remover</button>'; card.querySelector('.pname').value=p.name; card.querySelector('.pprompt').value=p.systemPrompt; card.querySelector('.remove').onclick=()=>{ if(settings.profiles.length===1)return status('Mantenha ao menos um perfil.',true); syncProfilesFromCards(); settings.profiles=settings.profiles.filter(x=>x.id!==p.id); renderProfiles(); }; $('profiles').append(card); } $('default-profile').value=settings.defaultProfileId; }
async function init(){try{settings=await window.assistant.getSettings();const g=settings.gateway;$('gateway-name').value=g.name;$('base-url').value=g.baseUrl;$('api-mode').value=g.apiMode;$('model').value=g.model;$('web-capable').checked=g.webSearchCapable;$('headers').value=Object.keys(g.extraHeaders).length?JSON.stringify(g.extraHeaders,null,2):'';$('key').placeholder=settings.hasApiKey?'Chave salva com segurança':'chave de API';renderProfiles();}catch(e){status(e.message,true)}}
$('save').onclick=async()=>{try{settings=await window.assistant.saveSettings({gateway:gatewayForm(),apiKey:$('key').value});$('key').value='';$('key').placeholder=settings.hasApiKey?'Chave salva com segurança':'chave de API';status('Gateway salvo.')}catch(e){status(e.message,true)}};
$('test').onclick=async()=>{try{status('Testando conexão…');await window.assistant.testConnection({gateway:gatewayForm(),apiKey:$('key').value});status('Conexão testada com sucesso.')}catch(e){status(e.message,true)}};
function syncProfilesFromCards(){const cards=[...document.querySelectorAll('.profile-card')];if(cards.length)settings.profiles=cards.map(c=>({id:c.dataset.id,name:c.querySelector('.pname').value,systemPrompt:c.querySelector('.pprompt').value}));}
$('add-profile').onclick=()=>{syncProfilesFromCards();const suffix=globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;settings.profiles.push({id:`perfil-${suffix}`,name:'Novo perfil',systemPrompt:'Você é um assistente cordial e objetivo.'});renderProfiles()};
$('save-profiles').onclick=async()=>{try{const profiles=[...document.querySelectorAll('.profile-card')].map(c=>({id:c.dataset.id,name:c.querySelector('.pname').value,systemPrompt:c.querySelector('.pprompt').value}));settings=await window.assistant.saveProfiles({profiles,defaultProfileId:$('default-profile').value});renderProfiles();status('Perfis salvos.')}catch(e){status(e.message,true)}};
for(const b of document.querySelectorAll('[data-prompt]'))b.onclick=()=>{$('instruction').value=b.dataset.prompt};
$('generate').onclick=async()=>{try{$('generate').disabled=true;captured=await window.assistant.capture();$('conversation').textContent=`Conversa atual: ${captured.title||captured.conversationId}`;const accountId=captured.accountId||'active';$('profile').value=await window.assistant.getSelection({accountId,conversationId:captured.conversationId});await window.assistant.setSelection({accountId,conversationId:captured.conversationId,profileId:$('profile').value});$('draft').value=await window.assistant.generate({context:captured,instruction:$('instruction').value,profileId:$('profile').value,webSearch:$('web').checked});status('Revise antes de inserir.')}catch(e){status(e.message,true)}finally{$('generate').disabled=false}};
$('profile').onchange=()=>{if(captured)window.assistant.setSelection({accountId:captured.accountId||'active',conversationId:captured.conversationId,profileId:$('profile').value}).catch(e=>status(e.message,true))};
$('insert').onclick=async()=>{try{if(!captured)throw new Error('Gere uma sugestão primeiro.');await window.assistant.insertDraft({conversationId:captured.conversationId,draft:$('draft').value});status('Rascunho inserido; revise e envie manualmente.')}catch(e){status(e.message,true)}};$('copy').onclick=()=>navigator.clipboard.writeText($('draft').value).then(()=>status('Copiado.')).catch(()=>status('Falha ao copiar.',true));$('close').onclick=()=>window.assistant.close();
const applyTheme=dark=>document.body.classList.toggle('theme-dark',!!dark);
if(window.assistant.getUiTheme)window.assistant.getUiTheme().then(applyTheme).catch(()=>{});
if(window.assistant.onUiTheme)window.assistant.onUiTheme(applyTheme);
init();
